name: game
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.4

# Add regular dependencies here.
dependencies:
  dart_console2: ^3.0.0
  json_annotation: ^4.8.0

dev_dependencies:  
  build_runner: ^2.3.3
  json_serializable: ^6.7.1
  lints: ^2.1.0
  test: ^1.24.0
